# Generated by Django 4.0.2 on 2022-03-13 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=115)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('vidio', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])])),
                ('privew', models.FileField(upload_to='media/')),
            ],
        ),
    ]
