# Generated by Django 4.0.2 on 2022-03-07 18:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=115)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('vidio', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'M4V', 'MOV', 'mxf'])])),
                ('privew', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Chenele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('datecreated', models.DateField(auto_now_add=True)),
                ('icon', models.ImageField(upload_to='')),
                ('backgtound', models.ImageField(upload_to='')),
                ('descprion', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vidio', models.ManyToManyField(to='main.Vidio')),
            ],
        ),
    ]
