# Generated by Django 4.0.2 on 2022-03-13 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidio',
            name='publick',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vidio',
            name='relateed_to_chenel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vidio',
            name='watched',
            field=models.BigIntegerField(default=0),
        ),
    ]
