# Generated by Django 4.0.2 on 2022-03-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_color_color_color_extra_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slag', models.SlugField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=1028)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='chapter_color',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='chapter_color2',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vidio',
            name='topik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chapter'),
        ),
    ]
