# Generated by Django 4.0.2 on 2022-03-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_vidio_topik_vidio_topik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
