# Generated by Django 4.0.2 on 2022-03-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_vidio_topik'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidio',
            name='content_is_18_plus',
            field=models.BooleanField(default=False),
        ),
    ]
