# Generated by Django 4.0.2 on 2022-03-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_vidio_content_is_18_plus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vidio',
            old_name='content_is_18_plus',
            new_name='content_is_only_18_plus',
        ),
    ]
