# Generated by Django 4.0.2 on 2022-03-29 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_content_is_18_plus_vidio_content_is_only_18_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidio',
            name='vidio',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'mkv'])]),
        ),
    ]
