# Generated by Django 4.0.2 on 2022-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_vidio_vidio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidio',
            name='for_gender',
            field=models.CharField(choices=[('Man', 'male'), ('Woman', 'female'), ('Other', 'Other')], max_length=8, null=True),
        ),
    ]
