# Generated by Django 4.0.2 on 2022-03-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_vidio_for_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vidio',
            name='for_gender',
        ),
    ]
