# Generated by Django 4.0.2 on 2022-03-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_vidio_for_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidio',
            name='vidio_for_gender',
            field=models.CharField(choices=[('Man', 'male'), ('Woman', 'female'), ('Other', 'Other')], default='Other', max_length=8),
        ),
    ]
