# Generated by Django 4.0.2 on 2022-03-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_vidio_vidio_for_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidio',
            name='vidio_for_gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Other', 'Other')], default='Other', max_length=8),
        ),
    ]
