# Generated by Django 4.0.2 on 2022-03-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAccount', '0002_remove_customuser_vidio_customuser_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Man', 'male'), ('Woman', 'female'), ('Other', 'Other')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.CharField(choices=[('PCGames', 'PC Games'), ('IT', 'IT'), ('Study', 'Study'), ('Musik', 'Musik'), ('Sports', 'Sports'), ('DIY', 'DIY'), ('Decor', 'Decor'), ('Feashion', 'Feashion'), ('Other', 'Other')], max_length=8, null=True),
        ),
    ]
