# Generated by Django 4.0.2 on 2022-03-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_vidio_content_is_18_plus'),
        ('MyAccount', '0004_remove_customuser_interests_customuser_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Man', 'male'), ('Woman', 'female'), ('Other', 'Other')], max_length=8),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(to='main.Chapter'),
        ),
    ]
