# Generated by Django 4.0.2 on 2022-03-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAccount', '0005_alter_customuser_gender_alter_customuser_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='backgtound',
            field=models.ImageField(blank=True, default='users_defult/depositphotos_56588069-stock-photo-earth-view-from-space-at.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, default='users_defult/05e93d6ba2e8e9076a51b5eece3a12f1_400x400.png', upload_to=''),
        ),
    ]
